### ISSUE TITLE
网络导入提示出错

### ISSUE THREAD

**Issue by byny** [ZWolken/Light-Novel-Yuedu-Source#14]
在使用最新版的阅读APP（3.25）导入该json文件的时候出现了如下错误候：
ImportError:java.lang.IllegalStateException: Expected BEGIN ARRAY but was BEGIN OBJECT at line 2 column 6 path $。
看起来似乎是源的写法改变了，请问阅读的哪一个版本可以正常的支持这些源文件？

**Comment by gongfuture** [comment]
我目前使用的就是3.25版本，稍等一会我测试一下导入

**Comment by gongfuture** [comment]
> 在使用最新版的阅读APP（3.25）导入该json文件的时候出现了如下错误候： ImportError:java.lang.IllegalStateException: Expected BEGIN ARRAY but was BEGIN OBJECT at line 2 column 6 path $。ImportError:java.lang.IllegalStateException: 第 2 行第 6 列路径$处预期 BEGIN ARRAY 但获取到的是 BEGIN OBJECT。 看起来似乎是源的写法改变了，请问阅读的哪一个版本可以正常的支持这些源文件？

我这里测试是可以正常导入
请问导入的是哪一个json？如果可以的话，能否提供完整的阅读日志？在`备份与恢复`中设置备份路径后点击`关于`中的`保存日志`

**Comment by ZWolken** [comment]
全新安装`3.25`版本，经测试可正常导入，问题无法复现。
该提示疑似JSON文件未正常获取，请检查网络环境是否可正常流畅访问GitHub域名下链接。
本人主要使用`3.23.051323`版本，不过软件版本应该不是造成问题的原因。

**Comment by gongfuture** [comment]
> 全新安装`3.25`版本，经测试可正常导入，问题无法复现。 该提示疑似JSON文件未正常获取，请检查网络环境是否可正常流畅访问GitHub域名下链接。 本人主要使用`3.23.051323`版本，不过软件版本应该不是造成问题的原因。

你来了我正好问下，我大刀阔斧的改动这个仓库没问题吧（）

**Comment by ZWolken** [comment]
> > 全新安装`3.25`版本，经测试可正常导入，问题无法复现。 该提示疑似JSON文件未正常获取，请检查网络环境是否可正常流畅访问GitHub域名下链接。 本人主要使用`3.23.051323`版本，不过软件版本应该不是造成问题的原因。
> 
> 你来了我正好问下，我大刀阔斧的改动这个仓库没问题吧（）

没事（）别把原有内容删了，建个文件夹丢进去就都行，`README`文件里的几个超链接记得按照文件路径修改一下。

**Comment by gongfuture** [comment]
> > > 全新安装`3.25`版本，经测试可正常导入，问题无法复现。 该提示疑似JSON文件未正常获取，请检查网络环境是否可正常流畅访问GitHub域名下链接。 本人主要使用`3.23.051323`版本，不过软件版本应该不是造成问题的原因。
> > 
> > 
> > 你来了我正好问下，我大刀阔斧的改动这个仓库没问题吧（）
> 
> 没事（）别把原有内容删了，建个文件夹丢进去就都行，`README`文件里的几个超链接记得按照文件路径修改一下。

ok

**Comment by byny** [comment]
在该项目点击code，选择“download zip”，下载解压完毕后，选择通过localsend软件发送到手机。

**Comment by gongfuture** [comment]
怎么又打开了？

**Comment by byny** [comment]
完全删除本机上的阅读APP，在阅读的github发布页：https://github.com/gedoor/legado/releases/tag/3.25 下载3.25版本后，安装到手机。
在本项目“code”下选择“download zip”，解压后选择“D:\BaiduNetdiskDownload\Light-Novel-Yuedu-Source-main\Light-Novel-Yuedu-Source-main\src\Japan_based_bookSource”中的“真白萌(建议科学).json”，通过localsend发送到手机，之后通过mt管理器校验，sha-256均为“2b3af4575b24c9bcae963b9127dc6fdd514fc1e17a80078fc126605e6638243c”，确定是同一文件后尝试在手机的阅读APP上导入。
仍旧出现提示“ImportError:java.lang.llegalStateException: Expected BEGIN ARRAY but was BEGIN OBJECT at line 2 column 6 path $”。

日志：
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 6 path $
at com.google.gson.d.n(SourceFile:67)
at com.google.gson.d.j(SourceFile:5)
at com.google.gson.d.i(SourceFile:5)
at io.legado.app.ui.association.o1.invokeSuspend(SourceFile:426)
at io.legado.app.ui.association.o1.invoke(SourceFile:2)
at io.legado.app.ui.association.o1.invoke(SourceFile:1)
at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:61)
at l8.a.resumeWith(SourceFile:9)at kotlinx.coroutines.j0.run(SourceFile:127)
at com.google.common.util.concurrent.u.h(SourceFile:6)
at com.google.common.util.concurrent.u.run(SourceFile:9)
at ka.k.run(SourceFile:3)
at ka.b.run(SourceFile:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 6 path 
$at l5.a.a(SourceFile:54)
at g5.b$a.f(SourceFile:22)
at g5.b$a.c(SourceFile:1)
at com.google.gson.d.n(SourceFile:19)... 12 more

怀疑是设备问题，在荣耀magic5pro，Motorola edge s，realme q2 5g，酷比魔方一代等4个设备上仍出现该问题。
是否是阅读版本下载错误？
哔哩轻小说log：“com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 6 path $at com.google.gson.d.n(SourceFile:67)at com.google.gson.d.j(SourceFile:5)at com.google.gson.d.i(SourceFile:5)at io.legado.app.ui.association.o1.invokeSuspend(SourceFile:426)at io.legado.app.ui.association.o1.invoke(SourceFile:2)at io.legado.app.ui.association.o1.invoke(SourceFile:1)at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:61)at l8.a.resumeWith(SourceFile:9)at kotlinx.coroutines.j0.run(SourceFile:127)at com.google.common.util.concurrent.u.h(SourceFile:6)at com.google.common.util.concurrent.u.run(SourceFile:9)at ka.k.run(SourceFile:3)at ka.b.run(SourceFile:96)Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 6 path $at l5.a.a(SourceFile:54)at g5.b$a.f(SourceFile:22)at g5.b$a.c(SourceFile:1)at com.google.gson.d.n(SourceFile:19)... 12 more”


缤纷幻想：“com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $at com.google.gson.d.n(SourceFile:67)at com.google.gson.d.j(SourceFile:5)at com.google.gson.d.i(SourceFile:5)at io.legado.app.ui.association.o1.invokeSuspend(SourceFile:426)at io.legado.app.ui.association.o1.invoke(SourceFile:2)at io.legado.app.ui.association.o1.invoke(SourceFile:1)at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:61)at l8.a.resumeWith(SourceFile:9)at kotlinx.coroutines.j0.run(SourceFile:127)at com.google.common.util.concurrent.u.h(SourceFile:6)at com.google.common.util.concurrent.u.run(SourceFile:9)at ka.k.run(SourceFile:3)at ka.b.run(SourceFile:96)Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $at l5.a.a(SourceFile:54)at g5.b$a.f(SourceFile:22)at g5.b$a.c(SourceFile:1)at com.google.gson.d.n(SourceFile:19)... 12 more”


轻小说百科：“com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $at com.google.gson.d.n(SourceFile:67)at com.google.gson.d.j(SourceFile:5)at com.google.gson.d.i(SourceFile:5)at io.legado.app.ui.association.o1.invokeSuspend(SourceFile:426)at io.legado.app.ui.association.o1.invoke(SourceFile:2)at io.legado.app.ui.association.o1.invoke(SourceFile:1)at io.legado.app.help.coroutine.i.invokeSuspend(SourceFile:61)at l8.a.resumeWith(SourceFile:9)at kotlinx.coroutines.j0.run(SourceFile:127)at com.google.common.util.concurrent.u.h(SourceFile:6)at com.google.common.util.concurrent.u.run(SourceFile:9)at ka.k.run(SourceFile:3)at ka.b.run(SourceFile:96)Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $at l5.a.a(SourceFile:54)at g5.b$a.f(SourceFile:22)at g5.b$a.c(SourceFile:1)at com.google.gson.d.n(SourceFile:19)... 12 more”

**Comment by gongfuture** [comment]
不是，你别用src里的啊，我还没整好呢（）
目前先用release的

**Comment by ZWolken** [comment]
请使用`Release`发行版内的书源文件进行本地/网络导入，仓库代码目录`src/`下的仍在编辑处理中，暂时不要使用。
