### ISSUE TITLE
搜索问题

### ISSUE THREAD

**Issue by ENIAC1729** [ZWolken/Light-Novel-Yuedu-Source#3]
你好,请问这个书源还在更新吗,我发现这个书源基本上不能进行搜索,只能一个个的找

**Comment by ZWolken** [comment]
大致是停坑了（忙于学业轻小说基本没看了）
您可以试试将哔哩轻小说地址改为`https://tw.linovelib.com`（该站点全为繁体，搜索也需要繁体输入）
ESJ轻小说地址改为`http://www.esjzone.me`
几个需要登录的源登录
推荐先去各个源的原网站搜索，搜到后将书名复制到阅读APP内在进行搜索，或者直接复制导入URL也可以
目前我自己使用下来哔哩轻小说、铅笔小说、轻之国度、ESJ、真白萌都是可以正常搜索使用的，您若无法解决或许可以去酷安评论区那边问问有没有大佬能修复，我号被封了就基本没再上酷安了。
